# Generated by Django 3.1.2 on 2020-10-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201014_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componentes', models.CharField(blank=True, choices=[('sel', 'Seleccione'), ('pma', 'Placa Madre'), ('pro', 'Procesador'), ('gpu', 'Targeta de Video'), ('ram', 'Ram'), ('alm', 'Almacenamiento'), ('fdp', 'Fuente de Poder'), ('gab', 'Gabinete'), ('mon', 'Monitor')], default='sel', help_text='Disponibilidad de Componente', max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='PlacaMadre',
        ),
    ]
