# Generated by Django 3.1.2 on 2020-10-14 22:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201014_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacaMadre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Codigo unido del producto', primary_key=True, serialize=False)),
                ('marca', models.CharField(choices=[('s', 'Seleccione'), ('m', 'MSI'), ('a', 'ASUS'), ('g', 'GIGABYTE')], default='s', help_text='Marca del producto', max_length=1)),
                ('modelo', models.CharField(max_length=100)),
                ('formato', models.CharField(choices=[('s', 'Seleccione'), ('a', 'ATX'), ('i', 'Mini ITX')], default='s', help_text='Formato de la Placa Madre', max_length=1)),
                ('plataforma', models.CharField(choices=[('se', 'Seleccione'), ('am', 'AMD'), ('in', 'Intel')], default='se', help_text='Plataforma de la Placa Madre', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
