# Generated by Django 3.1.2 on 2020-10-14 23:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20201014_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Codigo unico del producto', primary_key=True, serialize=False)),
                ('marca', models.CharField(choices=[('s', 'Seleccione'), ('a', 'AMD'), ('i', 'Intel')], default='s', help_text='Marca del producto', max_length=1)),
                ('modelo', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=50)),
                ('socket', models.CharField(choices=[('s', 'Seleccione'), ('l', 'LGA 1151-v2'), ('m', 'AM4'), ('t', 'TR4')], default='s', help_text='Socket del producto', max_length=1)),
                ('precio', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='placamadre',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='placamadre',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Codigo unico del producto', primary_key=True, serialize=False),
        ),
    ]
