# Generated by Django 3.1.2 on 2020-10-15 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_almacenamieto_fuentepoder_gpu_ram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gabinete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Codigo unico del producto', primary_key=True, serialize=False)),
                ('marca', models.CharField(choices=[('s', 'Seleccione'), ('i', 'In Win'), ('m', 'marvo')], default='s', help_text='Marca del producto', max_length=1)),
                ('modelo', models.CharField(max_length=50)),
                ('fuente_gabinete', models.CharField(choices=[('se', 'Seleccione'), ('np', 'No posee'), ('sp', 'Si posee')], default='se', help_text='Posee o no posee fuente de poder dentro del gabinete', max_length=2)),
                ('panel', models.CharField(choices=[('s', 'Seleccione'), ('v', 'Vidrio Templado'), ('a', 'Panel Acrilico')], default='s', help_text='Tipo de panel del gabinete', max_length=1)),
                ('precio', models.IntegerField(default=0)),
            ],
        ),
    ]
