# Generated by Django 3.1.2 on 2020-10-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_placasmadre_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placasmadre',
            name='url',
        ),
    ]
