# Generated by Django 3.1.2 on 2020-10-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_placasmadre_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placasmadre',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/piezas'),
        ),
    ]
