# Generated by Django 3.1.2 on 2020-10-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20201021_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placasmadre',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
