# Generated by Django 3.1.2 on 2020-10-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20201021_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placasmadre',
            name='imagen',
            field=models.ImageField(null=True, upload_to='placasmadres'),
        ),
    ]
