# Generated by Django 3.1.2 on 2020-10-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20201021_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placasmadre',
            name='imagen',
            field=models.ImageField(null=True, upload_to='placasmadres/'),
        ),
    ]
