# Generated by Django 3.1.2 on 2020-10-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20201021_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placasmadre',
            name='formato',
            field=models.CharField(choices=[('seleccione', 'Seleccione'), ('ATX', 'ATX'), ('Mini ITX', 'Mini ITX')], default='s', help_text='Formato de la Placa Madre', max_length=10),
        ),
        migrations.AlterField(
            model_name='placasmadre',
            name='marca',
            field=models.CharField(choices=[('seleccione', 'Seleccione'), ('MSI', 'MSI'), ('ASUS', 'ASUS'), ('GIGABYTE', 'GIGABYTE')], default='s', help_text='Marca del producto', max_length=10),
        ),
        migrations.AlterField(
            model_name='placasmadre',
            name='plataforma',
            field=models.CharField(choices=[('seleccione', 'Seleccione'), ('AMD', 'AMD'), ('Intel', 'Intel')], default='se', help_text='Plataforma de la Placa Madre', max_length=10),
        ),
    ]
