# Generated by Django 3.1.2 on 2020-10-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20201021_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placasmadre',
            name='formato',
            field=models.CharField(choices=[('seleccione', 'Seleccione'), ('ATX', 'ATX'), ('Mini ITX', 'Mini ITX'), ('Micro ATX', 'Micro ATX')], default='s', help_text='Formato de la Placa Madre', max_length=10),
        ),
        migrations.AlterField(
            model_name='placasmadre',
            name='marca',
            field=models.CharField(help_text='Marca del producto', max_length=100),
        ),
    ]
